// `apps/extension/dist/config.js` is generated by `scripts/build-extension.mjs`.
// Keep the source fallback pointed at the local backend so loading `src/` directly
// as an unpacked extension still works during development.
export const BACKEND_URL = "http://127.0.0.1:3001";
export const HOT_RELOAD_ENABLED = false;
export const HOT_RELOAD_URL = "http://127.0.0.1:35729";
