// `apps/extension/dist/config.js` is generated by `scripts/build-extension.mjs`.
// This source file is only a checked-in fallback for local linting and clarity.
export const BACKEND_URL = "https://vibe-pilotweb-production.up.railway.app";
export const HOT_RELOAD_ENABLED = false;
export const HOT_RELOAD_URL = "http://127.0.0.1:35729";
